#!/bin/bash

current_time=$(date +"%H:%M")
weekday_number=$(date +"%u") # %u gives weekday as 1 (Monday) to 7 (Sunday)

weekday_names=("Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday" "Sunday")

weekday_name=${weekday_names[$((weekday_number-1))]}

json_output="{\"now\":\"$current_time\",\"week\":\"$weekday_name\"}"

echo "$json_output"
